name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm install

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Clean Allure results
      run: npm run clean:allure

    - name: Run Playwright tests
      run: xvfb-run npm run test:demo_cr_he
      env:
        BASE_URL: "https://www.saucedemo.com/"
        USER_NAME: ${{ secrets.USER_NAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        PRODUCTPAGE_URL: "https://www.saucedemo.com/inventory.html"

    - name: Generate Allure Report
      if: ${{ !cancelled() }}
      run: npm run generate:allure

    - name: Upload Playwright Report
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

    - name: Upload Allure Report
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: allure-report
        path: allure-report/
        retention-days: 30
